// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// BookDeleter is an autogenerated mock type for the BookDeleter type
type BookDeleter struct {
	mock.Mock
}

// DeleteBook provides a mock function with given fields: ctx, id
func (_m *BookDeleter) DeleteBook(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
