// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	books "github.com/rafaelhl/library-rel-lib/books"

	mock "github.com/stretchr/testify/mock"
)

// BookFinder is an autogenerated mock type for the BookFinder type
type BookFinder struct {
	mock.Mock
}

// FindBook provides a mock function with given fields: ctx, bookID
func (_m *BookFinder) FindBook(ctx context.Context, bookID int) (books.Book, error) {
	ret := _m.Called(ctx, bookID)

	var r0 books.Book
	if rf, ok := ret.Get(0).(func(context.Context, int) books.Book); ok {
		r0 = rf(ctx, bookID)
	} else {
		r0 = ret.Get(0).(books.Book)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, bookID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
