// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	books "github.com/rafaelhl/library-rel-lib/books"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ShelfFinder is an autogenerated mock type for the ShelfFinder type
type ShelfFinder struct {
	mock.Mock
}

// FindShelf provides a mock function with given fields: ctx, shelfID
func (_m *ShelfFinder) FindShelf(ctx context.Context, shelfID int) (books.Shelf, error) {
	ret := _m.Called(ctx, shelfID)

	var r0 books.Shelf
	if rf, ok := ret.Get(0).(func(context.Context, int) books.Shelf); ok {
		r0 = rf(ctx, shelfID)
	} else {
		r0 = ret.Get(0).(books.Shelf)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, shelfID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
